# Generated by Django 4.2.8 on 2026-04-02 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoSuuTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bo_suu_tap', models.CharField(max_length=200, verbose_name='Tên bộ sưu tập')),
            ],
            options={
                'verbose_name': 'Bộ sưu tập',
                'verbose_name_plural': 'Bộ sưu tập',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nguoidung', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_the_loai', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
            },
        ),
        migrations.CreateModel(
            name='TheLoaiTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.theloai', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Thể loại - Truyện',
                'verbose_name_plural': 'Thể loại - Truyện',
            },
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_truyen', models.CharField(max_length=255, verbose_name='Tên truyện')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('trang_thai', models.CharField(choices=[('ban_thao', 'Bản thảo'), ('da_dang', 'Đã đăng'), ('hoan_thanh', 'Hoàn thành')], default='ban_thao', max_length=20, verbose_name='Trạng thái')),
                ('anh_bia', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Ảnh bìa')),
                ('so_luot_doc', models.PositiveIntegerField(default=0, verbose_name='Số lượt đọc')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_list', to='books.nguoidung', verbose_name='Tác giả')),
                ('the_loai', models.ManyToManyField(blank=True, related_name='truyen_list', through='books.TheLoaiTruyen', to='books.theloai', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Truyện',
                'verbose_name_plural': 'Truyện',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='theloaitruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(blank=True, verbose_name='Nội dung')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('trang_thai', models.CharField(choices=[('ban_thao', 'Bản thảo'), ('da_dang', 'Đã đăng tải')], default='ban_thao', max_length=20, verbose_name='Trạng thái')),
                ('thoi_gian_dang', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuong_list', to='books.truyen', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Chương',
                'verbose_name_plural': 'Chương',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoSuuTapTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_suu_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bosuutap', verbose_name='Bộ sưu tập')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Bộ sưu tập - Truyện',
                'verbose_name_plural': 'Bộ sưu tập - Truyện',
                'unique_together': {('bo_suu_tap', 'truyen')},
            },
        ),
        migrations.AddField(
            model_name='bosuutap',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bo_suu_tap_list', to='books.nguoidung', verbose_name='Chủ sở hữu'),
        ),
        migrations.AddField(
            model_name='bosuutap',
            name='truyen_list',
            field=models.ManyToManyField(blank=True, related_name='bo_suu_tap_list', through='books.BoSuuTapTruyen', to='books.truyen', verbose_name='Danh sách truyện'),
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('thoi_gian_bl', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bình luận')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan_list', to='books.nguoidung', verbose_name='Người dùng')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan_list', to='books.truyen', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-thoi_gian_bl'],
            },
        ),
        migrations.CreateModel(
            name='TheoDoiTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi_truyen_list', to='books.nguoidung', verbose_name='Người dùng')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi_list', to='books.truyen', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Theo dõi truyện',
                'verbose_name_plural': 'Theo dõi truyện',
                'unique_together': {('nguoi_dung', 'truyen')},
            },
        ),
        migrations.CreateModel(
            name='TheoDoiNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_duoc_theo_doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_theo_doi_list', to='books.nguoidung', verbose_name='Người được theo dõi')),
                ('nguoi_theo_doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_theo_doi', to='books.nguoidung', verbose_name='Người theo dõi')),
            ],
            options={
                'verbose_name': 'Theo dõi người dùng',
                'verbose_name_plural': 'Theo dõi người dùng',
                'unique_together': {('nguoi_theo_doi', 'nguoi_duoc_theo_doi')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='theloaitruyen',
            unique_together={('truyen', 'the_loai')},
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sao_danh_gia', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Số sao')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to='books.nguoidung', verbose_name='Người dùng')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to='books.truyen', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'unique_together': {('nguoi_dung', 'truyen')},
            },
        ),
    ]
