# Generated by Django 4.2.8 on 2026-04-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('chuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_doc_list', to='books.chuong', verbose_name='Chương đang đọc')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doc_list', to='books.nguoidung', verbose_name='Người dùng')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doc_list', to='books.truyen', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Lịch sử đọc',
                'verbose_name_plural': 'Lịch sử đọc',
                'ordering': ['-updated_at'],
                'unique_together': {('nguoi_dung', 'truyen')},
            },
        ),
    ]
