# Generated by Django 5.2.13 on 2026-04-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_lich_su_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binhluan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bosuutap',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bosuutaptruyen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chuong',
            options={},
        ),
        migrations.AlterModelOptions(
            name='danhgia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lichsudoc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={},
        ),
        migrations.AlterModelOptions(
            name='theloai',
            options={},
        ),
        migrations.AlterModelOptions(
            name='theloaitruyen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='theodoinguoidung',
            options={},
        ),
        migrations.AlterModelOptions(
            name='theodoitruyen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='truyen',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='truyen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày đăng'),
        ),
        migrations.AddField(
            model_name='truyen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Cập nhật mới nhất'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='noi_dung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='thoi_gian_bl',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan_list', to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='bosuutap',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bo_suu_tap_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='bosuutap',
            name='ten_bo_suu_tap',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bosuutap',
            name='truyen_list',
            field=models.ManyToManyField(blank=True, related_name='bo_suu_tap_list', through='books.BoSuuTapTruyen', to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='bosuutaptruyen',
            name='bo_suu_tap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bosuutap'),
        ),
        migrations.AlterField(
            model_name='bosuutaptruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='noi_dung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='thoi_gian_dang',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='tieu_de',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='trang_thai',
            field=models.CharField(choices=[('ban_thao', 'Bản thảo'), ('da_dang', 'Đã đăng tải')], default='ban_thao', max_length=20),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuong_list', to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='sao_danh_gia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='chuong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.chuong'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doc_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doc_list', to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nguoidung', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theloai',
            name='ten_the_loai',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='theloaitruyen',
            name='the_loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.theloai'),
        ),
        migrations.AlterField(
            model_name='theloaitruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='theodoinguoidung',
            name='nguoi_duoc_theo_doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_theo_doi_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='theodoinguoidung',
            name='nguoi_theo_doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_theo_doi', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='theodoitruyen',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi_truyen_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='theodoitruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi_list', to='books.truyen'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='anh_bia',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='mo_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_list', to='books.nguoidung'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='so_luot_doc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='ten_truyen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='the_loai',
            field=models.ManyToManyField(blank=True, related_name='truyen_list', through='books.TheLoaiTruyen', to='books.theloai'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='trang_thai',
            field=models.CharField(choices=[('ban_thao', 'Bản thảo'), ('dang_tien_hanh', 'Đang tiến hành'), ('hoan_thanh', 'Hoàn thành')], default='ban_thao', max_length=20),
        ),
    ]
