# Generated by Django 5.2.13 on 2026-04-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_lich_su_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuong',
            name='so_luot_binh_luan',
            field=models.PositiveIntegerField(default=0, verbose_name='Số bình luận'),
        ),
        migrations.AddField(
            model_name='chuong',
            name='so_luot_doc',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượt đọc'),
        ),
        migrations.AddField(
            model_name='chuong',
            name='so_luot_luu',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượt lưu'),
        ),
    ]
