# Generated by Django 4.2.8 on 2026-04-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_binhluan_options_alter_bosuutap_options_and_more'),
        ('books', '0003_chuong_so_luot_binh_luan_chuong_so_luot_doc_and_more'),
    ]

    operations = [
    ]
