# Generated by Django 4.2.8 on 2026-04-26 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_merge_20260426_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binhluan',
            options={'verbose_name': 'Bình luận', 'verbose_name_plural': 'Bình luận'},
        ),
        migrations.AlterModelOptions(
            name='bosuutap',
            options={'verbose_name': 'Bộ sưu tập', 'verbose_name_plural': 'Bộ sưu tập'},
        ),
        migrations.AlterModelOptions(
            name='bosuutaptruyen',
            options={'verbose_name': 'Bộ sưu tập - Truyện', 'verbose_name_plural': 'Bộ sưu tập - Truyện'},
        ),
        migrations.AlterModelOptions(
            name='chuong',
            options={'ordering': ['id'], 'verbose_name': 'Chương', 'verbose_name_plural': 'Chương'},
        ),
        migrations.AlterModelOptions(
            name='danhgia',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='lichsudoc',
            options={'verbose_name': 'Lịch sử đọc', 'verbose_name_plural': 'Lịch sử đọc'},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='theloai',
            options={'verbose_name': 'Thể loại', 'verbose_name_plural': 'Thể loại'},
        ),
        migrations.AlterModelOptions(
            name='theloaitruyen',
            options={'verbose_name': 'Thể loại - Truyện', 'verbose_name_plural': 'Thể loại - Truyện'},
        ),
        migrations.AlterModelOptions(
            name='theodoinguoidung',
            options={'verbose_name': 'Theo dõi người dùng', 'verbose_name_plural': 'Theo dõi người dùng'},
        ),
        migrations.AlterModelOptions(
            name='theodoitruyen',
            options={'verbose_name': 'Theo dõi truyện', 'verbose_name_plural': 'Theo dõi truyện'},
        ),
        migrations.AlterModelOptions(
            name='truyen',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Truyện', 'verbose_name_plural': 'Truyện'},
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.nguoidung', verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='noi_dung',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='thoi_gian_bl',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bình luận'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='bosuutap',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bo_suu_tap_list', to='books.nguoidung', verbose_name='Chủ sở hữu'),
        ),
        migrations.AlterField(
            model_name='bosuutap',
            name='ten_bo_suu_tap',
            field=models.CharField(max_length=200, verbose_name='Tên bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='bosuutap',
            name='truyen_list',
            field=models.ManyToManyField(blank=True, related_name='bo_suu_tap_list', through='books.BoSuuTapTruyen', to='books.truyen', verbose_name='Danh sách truyện'),
        ),
        migrations.AlterField(
            model_name='bosuutaptruyen',
            name='bo_suu_tap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bosuutap', verbose_name='Bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='bosuutaptruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='noi_dung',
            field=models.TextField(blank=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='thoi_gian_dang',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='tieu_de',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='trang_thai',
            field=models.CharField(choices=[('ban_thao', 'Bản thảo'), ('da_dang', 'Đã đăng tải')], default='ban_thao', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuong_list', to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.nguoidung', verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='sao_danh_gia',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Số sao'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='chuong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.chuong', verbose_name='Chương đang đọc'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doc_list', to='books.nguoidung', verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doc_list', to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nguoidung', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AlterField(
            model_name='theloai',
            name='ten_the_loai',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại'),
        ),
        migrations.AlterField(
            model_name='theloaitruyen',
            name='the_loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.theloai', verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='theloaitruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='theodoinguoidung',
            name='nguoi_duoc_theo_doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_theo_doi_list', to='books.nguoidung', verbose_name='Người được theo dõi'),
        ),
        migrations.AlterField(
            model_name='theodoinguoidung',
            name='nguoi_theo_doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_theo_doi', to='books.nguoidung', verbose_name='Người theo dõi'),
        ),
        migrations.AlterField(
            model_name='theodoitruyen',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.nguoidung', verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='theodoitruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.truyen', verbose_name='Truyện'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='anh_bia',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='mo_ta',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_list', to='books.nguoidung', verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='so_luot_doc',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượt đọc'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='ten_truyen',
            field=models.CharField(max_length=255, verbose_name='Tên truyện'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='the_loai',
            field=models.ManyToManyField(blank=True, related_name='truyen_list', through='books.TheLoaiTruyen', to='books.theloai', verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='trang_thai',
            field=models.CharField(choices=[('ban_thao', 'Bản thảo'), ('da_dang', 'Đã đăng'), ('hoan_thanh', 'Hoàn thành')], default='ban_thao', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
