# Generated by Django 4.2.8 on 2026-04-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_binhluan_options_alter_bosuutap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theodoitruyen',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi_truyen_list', to='books.nguoidung', verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='theodoitruyen',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi_list', to='books.truyen', verbose_name='Truyện'),
        ),
    ]
